In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
import pickle

In [7]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [8]:
data = data.drop(['RowNumber','CustomerId','Surname'], axis=1)

In [9]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [10]:
from sklearn.preprocessing import OneHotEncoder
# Initialize One-Hot Encoder
onehot_encoder_geo = OneHotEncoder(sparse_output=False)

# Fit and transform the Geography column
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']])

# Convert to DataFrame
geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=onehot_encoder_geo.get_feature_names_out(['Geography']),
    index=data.index
)

# Drop original Geography column and concatenate encoded columns
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)

In [11]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [13]:
X = data.drop('EstimatedSalary', axis = 1)
y = data['EstimatedSalary']

In [14]:
X

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 12 columns]

In [15]:
y

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [17]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)   # Linear activation by default
])

WARNING:tensorflow:From c:\ANN_Classification_Project\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From c:\ANN_Classification_Project\venv\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

In [19]:
model.compile(optimizer='adam', loss='mean_absolute_error',metrics=['mae'])

WARNING:tensorflow:From c:\ANN_Classification_Project\venv\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [22]:
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None

In [23]:
import datetime
from tensorflow.keras.callbacks import TensorBoard

log_dir = "logs/regression/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [24]:
from tensorflow.keras.callbacks import EarlyStopping

early_stopping_callback = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

In [25]:
history = model.fit(
    X_train,
    y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[tensorboard_callback, early_stopping_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\ANN_Classification_Project\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\ANN_Classification_Project\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 3s 6ms/step - loss: 100379.3281 - mae: 100379.3281 - val_loss: 98523.0625 - val_mae: 98523.0625
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 99639.7734 - mae: 99639.7734 - val_loss: 97009.0703 - val_mae: 97009.0703
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 96968.5391 - mae: 96968.5391 - val_loss: 93069.3828 - val_mae: 93069.3828
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 91658.3672 - mae: 91658.3672 - val_loss: 86467.3594 - val_mae: 86467.3594
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 83907.3750 - mae: 83907.3750 - val_loss: 77983.7734 - val_mae: 77983.7734
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 74809.4453 - mae: 74809.4453 - val_loss: 69233.9453 - val_mae: 69233.9453
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 65994.6484 - mae: 65994.6484 - val_loss: 61559.7148 - val_mae: 61559.7148
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 58944.6367 - mae: 58944.6367 - val_loss: 56094.8320 - val_mae: 56094.8320
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 54383.7109 - mae: 54383.7109 - val_loss: 52902.5078 - val_mae: 52902.5078
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 51931.6523 - mae: 51931.6523 - val_loss: 51586.1641 - val_mae: 51586.1641
Epoch 11/100
250/250 [==============================] - 1s 3ms/step - loss: 50910.9258 - mae: 50910.9258 - val_loss: 51202.6875 - val_mae: 51202.6875
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 50542.6484 - mae: 50542.6484 - val_loss: 51064.7969 - val_mae: 51064.7969
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 50383.0508 - mae: 50383.0508 - val_loss: 50991.9922 - val_mae: 50991.9922
Epoch 14/100
250/250 [==============================] - 1s 3ms/step - loss: 50301.1289 - mae: 50301.1289 - val_loss: 50922.7734 - val_mae: 50922.7734
Epoch 15/100
250/250 [==============================] - 1s 3ms/step - loss: 50233.6523 - mae: 50233.6523 - val_loss: 50859.0625 - val_mae: 50859.0625
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 50176.0781 - mae: 50176.0781 - val_loss: 50804.3320 - val_mae: 50804.3320
Epoch 17/100
250/250 [==============================] - 1s 3ms/step - loss: 50125.7891 - mae: 50125.7891 - val_loss: 50758.6875 - val_mae: 50758.6875
Epoch 18/100
250/250 [==============================] - 1s 3ms/step - loss: 50083.2266 - mae: 50083.2266 - val_loss: 50723.8594 - val_mae: 50723.8594
Epoch 19/100
250/250 [==============================] - 1s 3ms/step - loss: 50039.1133 - mae: 50039.1133 - val_loss: 50691.2266 - val_mae: 50691.2266
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 50004.9844 - mae: 50004.9844 - val_loss: 50654.8477 - val_mae: 50654.8477
Epoch 21/100
250/250 [==============================] - 1s 3ms/step - loss: 49969.0898 - mae: 49969.0898 - val_loss: 50623.6328 - val_mae: 50623.6328
Epoch 22/100
250/250 [==============================] - 1s 3ms/step - loss: 49939.5977 - mae: 49939.5977 - val_loss: 50606.6641 - val_mae: 50606.6641
Epoch 23/100
250/250 [==============================] - 1s 3ms/step - loss: 49907.8516 - mae: 49907.8516 - val_loss: 50582.0430 - val_mae: 50582.0430
Epoch 24/100
250/250 [==============================] - 1s 3ms/step - loss: 49878.5117 - mae: 49878.5117 - val_loss: 50558.5156 - val_mae: 50558.5156
Epoch 25/100
250/250 [==============================] - 1s 3ms/step - loss: 49855.3945 - mae: 49855.3945 - val_loss: 50539.7344 - val_mae: 50539.7344
Epoch 26/100
250/250 [==============================] - 1s 3ms/step - loss: 49832.6133 - mae: 49832.6133 - val_loss: 50522.7656 - val_mae: 50522.7656
Epoch 27/100
250/250 [==============================] - 1s 3ms/step - loss: 49807.6484 - mae: 49807.6484 - val_loss: 50507.0000 - val_mae: 50507.0000
Epoch 28/100
250/250 [==============================] - 1s 4ms/step - loss: 49783.7305 - mae: 49783.7305 - val_loss: 50495.2812 - val_mae: 50495.2812
Epoch 29/100
250/250 [==============================] - 1s 3ms/step - loss: 49763.3164 - mae: 49763.3164 - val_loss: 50478.0234 - val_mae: 50478.0234
Epoch 30/100
250/250 [==============================] - 1s 3ms/step - loss: 49745.0547 - mae: 49745.0547 - val_loss: 50454.4844 - val_mae: 50454.4844
Epoch 31/100
250/250 [==============================] - 1s 3ms/step - loss: 49727.1680 - mae: 49727.1680 - val_loss: 50450.1289 - val_mae: 50450.1289
Epoch 32/100
250/250 [==============================] - 1s 4ms/step - loss: 49708.8047 - mae: 49708.8047 - val_loss: 50437.6016 - val_mae: 50437.6016
Epoch 33/100
250/250 [==============================] - 1s 3ms/step - loss: 49694.8867 - mae: 49694.8867 - val_loss: 50429.6641 - val_mae: 50429.6641
Epoch 34/100
250/250 [==============================] - 1s 3ms/step - loss: 49682.9648 - mae: 49682.9648 - val_loss: 50418.6797 - val_mae: 50418.6797
Epoch 35/100
250/250 [==============================] - 1s 3ms/step - loss: 49665.1875 - mae: 49665.1875 - val_loss: 50412.4922 - val_mae: 50412.4922
Epoch 36/100
250/250 [==============================] - 1s 4ms/step - loss: 49655.4492 - mae: 49655.4492 - val_loss: 50396.8438 - val_mae: 50396.8438
Epoch 37/100
250/250 [==============================] - 1s 3ms/step - loss: 49639.2383 - mae: 49639.2383 - val_loss: 50386.2539 - val_mae: 50386.2539
Epoch 38/100
250/250 [==============================] - 1s 3ms/step - loss: 49625.9688 - mae: 49625.9688 - val_loss: 50382.1406 - val_mae: 50382.1406
Epoch 39/100
250/250 [==============================] - 1s 3ms/step - loss: 49613.8047 - mae: 49613.8047 - val_loss: 50378.1641 - val_mae: 50378.1641
Epoch 40/100
250/250 [==============================] - 1s 4ms/step - loss: 49601.0547 - mae: 49601.0547 - val_loss: 50376.8516 - val_mae: 50376.8516
Epoch 41/100
250/250 [==============================] - 1s 3ms/step - loss: 49589.3203 - mae: 49589.3203 - val_loss: 50369.0117 - val_mae: 50369.0117
Epoch 42/100
250/250 [==============================] - 1s 3ms/step - loss: 49576.6641 - mae: 49576.6641 - val_loss: 50363.2930 - val_mae: 50363.2930
Epoch 43/100
250/250 [==============================] - 1s 3ms/step - loss: 49567.7969 - mae: 49567.7969 - val_loss: 50352.1484 - val_mae: 50352.1484
Epoch 44/100
250/250 [==============================] - 1s 3ms/step - loss: 49558.4023 - mae: 49558.4023 - val_loss: 50355.6055 - val_mae: 50355.6055
Epoch 45/100
250/250 [==============================] - 1s 3ms/step - loss: 49547.9844 - mae: 49547.9844 - val_loss: 50362.9844 - val_mae: 50362.9844
Epoch 46/100
250/250 [==============================] - 1s 3ms/step - loss: 49538.7422 - mae: 49538.7422 - val_loss: 50352.2930 - val_mae: 50352.2930
Epoch 47/100
250/250 [==============================] - 1s 3ms/step - loss: 49524.9648 - mae: 49524.9648 - val_loss: 50361.1055 - val_mae: 50361.1055
Epoch 48/100
250/250 [==============================] - 1s 4ms/step - loss: 49515.6289 - mae: 49515.6289 - val_loss: 50350.1953 - val_mae: 50350.1953
Epoch 49/100
250/250 [==============================] - 1s 3ms/step - loss: 49508.2773 - mae: 49508.2773 - val_loss: 50343.8242 - val_mae: 50343.8242
Epoch 50/100
250/250 [==============================] - 1s 3ms/step - loss: 49501.9727 - mae: 49501.9727 - val_loss: 50340.4297 - val_mae: 50340.4297
Epoch 51/100
250/250 [==============================] - 1s 3ms/step - loss: 49494.6133 - mae: 49494.6133 - val_loss: 50339.5000 - val_mae: 50339.5000
Epoch 52/100
250/250 [==============================] - 1s 3ms/step - loss: 49485.1289 - mae: 49485.1289 - val_loss: 50345.7266 - val_mae: 50345.7266
Epoch 53/100
250/250 [==============================] - 1s 3ms/step - loss: 49480.4531 - mae: 49480.4531 - val_loss: 50348.4219 - val_mae: 50348.4219
Epoch 54/100
250/250 [==============================] - 1s 3ms/step - loss: 49472.7617 - mae: 49472.7617 - val_loss: 50344.7695 - val_mae: 50344.7695
Epoch 55/100
250/250 [==============================] - 1s 3ms/step - loss: 49468.4492 - mae: 49468.4492 - val_loss: 50342.7422 - val_mae: 50342.7422
Epoch 56/100
250/250 [==============================] - 1s 3ms/step - loss: 49459.1406 - mae: 49459.1406 - val_loss: 50335.1719 - val_mae: 50335.1719
Epoch 57/100
250/250 [==============================] - 1s 4ms/step - loss: 49454.3438 - mae: 49454.3438 - val_loss: 50349.1523 - val_mae: 50349.1523
Epoch 58/100
250/250 [==============================] - 1s 3ms/step - loss: 49449.0312 - mae: 49449.0312 - val_loss: 50352.0039 - val_mae: 50352.0039
Epoch 59/100
250/250 [==============================] - 1s 4ms/step - loss: 49443.2031 - mae: 49443.2031 - val_loss: 50340.8711 - val_mae: 50340.8711
Epoch 60/100
250/250 [==============================] - 1s 5ms/step - loss: 49439.3555 - mae: 49439.3555 - val_loss: 50336.3242 - val_mae: 50336.3242
Epoch 61/100
250/250 [==============================] - 1s 4ms/step - loss: 49432.7773 - mae: 49432.7773 - val_loss: 50339.1602 - val_mae: 50339.1602
Epoch 62/100
250/250 [==============================] - 1s 3ms/step - loss: 49429.8281 - mae: 49429.8281 - val_loss: 50346.8867 - val_mae: 50346.8867
Epoch 63/100
250/250 [==============================] - 1s 4ms/step - loss: 49427.2109 - mae: 49427.2109 - val_loss: 50341.1406 - val_mae: 50341.1406
Epoch 64/100
250/250 [==============================] - 1s 3ms/step - loss: 49423.3945 - mae: 49423.3945 - val_loss: 50339.4492 - val_mae: 50339.4492
Epoch 65/100
250/250 [==============================] - 1s 3ms/step - loss: 49412.8320 - mae: 49412.8320 - val_loss: 50341.1523 - val_mae: 50341.1523
Epoch 66/100
250/250 [==============================] - 1s 3ms/step - loss: 49409.7539 - mae: 49409.7539 - val_loss: 50340.6016 - val_mae: 50340.6016

In [26]:
%load_ext tensorboard

In [27]:
%tensorboard --logdir logs/regression

In [28]:
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f'Test MAE: {test_mae}')

63/63 [==============================] - 0s 3ms/step - loss: 50335.1719 - mae: 50335.1719
Test MAE: 50335.171875